### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by maufc** [harihanv/esp32-modbus-gateway#2]
Hi.
I am looking for a functional modbus gateway for esp32.
I know it comes from arduino-modbus-gateway but I can't get a working version.
The error is the same: SERIAL_PORT_HARDWARE is not define in this scope.
I guess arduinors485.h does not work for esp32.
I am working with esp32 development board.
Thanks!

**Comment by agisofttm** [comment]
Just download library from other repository of @harihanv and compile it again - it work

**Comment by maufc** [comment]
Thanks! I did what you @agisofttm said.
I tried and make it work after some hardware trials because I am using some Wemos D1 R32 board.
There are some bugs well explained by you in the other topic.
I think this could be a solution for many cases. 
Thanks for your job @harihanv !

**Comment by harihanv** [comment]
please check if this rs485 works

**Comment by maufc** [comment]
Hi. I don't get it. What are yor refering to?
