### ISSUE TITLE
Any Update

### ISSUE THREAD

**Issue by barfiii** [harihanv/esp32-modbus-gateway#5]
Harish bro , do you have update of the code ?

**Comment by harihanv** [comment]
What exactly you are

**Comment by barfiii** [comment]
About those generateMac(),CreateTrulyRandomSeed() functions in interfaces.ino .

**Comment by harihanv** [comment]
It has been a long time since I have looked at it.

**Comment by barfiii** [comment]
Ok bro , No problem. Thank you.
